# Importing Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Importing Dataset

In [2]:
df=pd.read_csv('/content/drive/MyDrive/ML Tasks/ADG-ML/data.csv')

In [3]:
df.head(5)

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [4]:
df.tail(5)

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
564  926424         M  ...                  0.07115          NaN
565  926682         M  ...                  0.06637          NaN
566  926954         M  ...                  0.07820          NaN
567  927241         M  ...                  0.12400          NaN
568   92751         B  ...                  0.07039          NaN

[5 rows x 33 columns]

In [5]:
#copying the datset values into another variable
df1=df.copy()
df1.head(5)

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Encoding the data

In [8]:
from sklearn.preprocessing import LabelEncoder
encode=LabelEncoder()
df1['encode_diag']=encode.fit_transform(df['diagnosis'])
df1['diagnosis']=df1['encode_diag']
df1.head(5)

id  diagnosis  ...  Unnamed: 32  encode_diag
0    842302          1  ...          NaN            1
1    842517          1  ...          NaN            1
2  84300903          1  ...          NaN            1
3  84348301          1  ...          NaN            1
4  84358402          1  ...          NaN            1

[5 rows x 34 columns]

# Getting the useful data

In [9]:
df_clean=df1.drop(['id','Unnamed: 32'],axis='columns')
df_clean.head(5)

diagnosis  radius_mean  ...  fractal_dimension_worst  encode_diag
0          1        17.99  ...                  0.11890            1
1          1        20.57  ...                  0.08902            1
2          1        19.69  ...                  0.08758            1
3          1        11.42  ...                  0.17300            1
4          1        20.29  ...                  0.07678            1

[5 rows x 32 columns]

# Splitting the dependent and independent variables

In [10]:
x=df_clean.iloc[:,1:-1]
x.head(5)

radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [11]:
y=df_clean.iloc[:,31]
y.head(5)

0    1
1    1
2    1
3    1
4    1
Name: encode_diag, dtype: int64

# Splitting into training and test dataset

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.26,random_state=0)

In [13]:
x_train.count()

radius_mean                421
texture_mean               421
perimeter_mean             421
area_mean                  421
smoothness_mean            421
compactness_mean           421
concavity_mean             421
concave points_mean        421
symmetry_mean              421
fractal_dimension_mean     421
radius_se                  421
texture_se                 421
perimeter_se               421
area_se                    421
smoothness_se              421
compactness_se             421
concavity_se               421
concave points_se          421
symmetry_se                421
fractal_dimension_se       421
radius_worst               421
texture_worst              421
perimeter_worst            421
area_worst                 421
smoothness_worst           421
compactness_worst          421
concavity_worst            421
concave points_worst       421
symmetry_worst             421
fractal_dimension_worst    421
dtype: int64

In [14]:
y_train.count()

421

# Training the RandomForest onto to the dataset

In [15]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(random_state=0)
classifier.fit(x_train,y_train)
classifier.score(x_test,y_test)

0.972972972972973

In [16]:
y_pred=classifier.predict(x_test)

In [17]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.97      0.98        93
           1       0.95      0.98      0.96        55

    accuracy                           0.97       148
   macro avg       0.97      0.97      0.97       148
weighted avg       0.97      0.97      0.97       148



In [18]:
print(confusion_matrix(y_test,y_pred))

[[90  3]
 [ 1 54]]


# Training Logistic regression onto the dataset

In [19]:
from sklearn.linear_model import LogisticRegression
regressor=LogisticRegression(random_state=0,max_iter=171)
regressor.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=171,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [20]:
y_pred=regressor.predict(x_test)

In [21]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.95      0.97        93
           1       0.92      0.98      0.95        55

    accuracy                           0.96       148
   macro avg       0.95      0.96      0.96       148
weighted avg       0.96      0.96      0.96       148



In [22]:
print(confusion_matrix(y_test,y_pred))

[[88  5]
 [ 1 54]]


In [23]:
regressor.score(x_test,y_test)

0.9594594594594594

# GridSearchCV RandomForestClassifier

In [24]:
from sklearn.model_selection import GridSearchCV
clf=GridSearchCV(RandomForestClassifier(),{'n_estimators':[10,50,100]},cv=5,return_train_score='False')
clf.fit(x,y)

GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False,
                                              rando

In [25]:
df=pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  ...  mean_train_score  std_train_score
0       0.030315      0.009068  ...          0.997364         0.000880
1       0.113079      0.008546  ...          0.999122         0.001076
2       0.211953      0.008076  ...          1.000000         0.000000

[3 rows x 21 columns]

In [26]:
df[['params','mean_test_score']]

params  mean_test_score
0   {'n_estimators': 10}         0.952585
1   {'n_estimators': 50}         0.961372
2  {'n_estimators': 100}         0.959618

In [27]:
#training again to confirm values
classifier1=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False)
classifier1.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [28]:
y_pred1=classifier1.predict(x_test)

In [29]:
classifier1.score(x_test,y_test)

0.9594594594594594

In [30]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97        93
           1       0.95      0.95      0.95        55

    accuracy                           0.96       148
   macro avg       0.96      0.96      0.96       148
weighted avg       0.96      0.96      0.96       148



In [31]:
print(confusion_matrix(y_test,y_pred1))

[[90  3]
 [ 3 52]]


# GridSearchCV LogisticRegression

In [32]:
from sklearn.model_selection import GridSearchCV
reg=GridSearchCV(LogisticRegression(),{'C':[1,5,10]},cv=5,return_train_score='False')
reg.fit(x,y)

GridSearchCV(cv=5, error_score=nan,
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='deprecated', n_jobs=None, param_grid={'C': [1, 5, 10]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score='False',
             scoring=None, verbose=0)

In [33]:
df=pd.DataFrame(reg.cv_results_)
df

mean_fit_time  std_fit_time  ...  mean_train_score  std_train_score
0       0.049599      0.004743  ...          0.949474         0.009109
1       0.046547      0.006925  ...          0.951233         0.006407
2       0.046552      0.008590  ...          0.949916         0.008698

[3 rows x 21 columns]

In [34]:
df[['params','mean_test_score']]

params  mean_test_score
0   {'C': 1}         0.943766
1   {'C': 5}         0.943798
2  {'C': 10}         0.934964

In [35]:
reg1=LogisticRegression(C=1, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False)
reg1.fit(x_train,y_train)

LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [36]:
y_pred2=reg1.predict(x_test)

In [37]:
reg1.score(x_test,y_test)

0.9459459459459459

In [38]:
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.98      0.94      0.96        93
           1       0.90      0.96      0.93        55

    accuracy                           0.95       148
   macro avg       0.94      0.95      0.94       148
weighted avg       0.95      0.95      0.95       148



In [39]:
print(confusion_matrix(y_test,y_pred2))

[[87  6]
 [ 2 53]]


# RandomSearchCV RandomForestclassifier

In [40]:
from sklearn.model_selection import RandomizedSearchCV
clf1=RandomizedSearchCV(RandomForestClassifier(),{'n_estimators':[10,50,100]},cv=5,return_train_score='False',n_iter=3)
clf1.fit(x,y)

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
               

In [41]:
df=pd.DataFrame(clf1.cv_results_)
df

mean_fit_time  std_fit_time  ...  mean_train_score  std_train_score
0       0.025559      0.004773  ...          0.996924         0.002242
1       0.110474      0.008933  ...          1.000000         0.000000
2       0.212413      0.007804  ...          1.000000         0.000000

[3 rows x 21 columns]

In [42]:
df[['params','mean_test_score']]

params  mean_test_score
0   {'n_estimators': 10}         0.949061
1   {'n_estimators': 50}         0.961372
2  {'n_estimators': 100}         0.963111

In [43]:
#training again to confirm values
classifier2=RandomForestClassifier(bootstrap=True,
                                                    ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
                                                    n_estimators=100,
                                                    n_jobs=None,
                                                    oob_score=False,
                                                    random_state=None,
                                                    verbose=0,
                                                    warm_start=False)
classifier2.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [44]:
y_pred3=classifier2.predict(x_test)

In [45]:
classifier2.score(x_test,y_test)

0.9662162162162162

In [46]:
print(classification_report(y_test,y_pred3))

              precision    recall  f1-score   support

           0       0.97      0.98      0.97        93
           1       0.96      0.95      0.95        55

    accuracy                           0.97       148
   macro avg       0.97      0.96      0.96       148
weighted avg       0.97      0.97      0.97       148



In [47]:
print(confusion_matrix(y_test,y_pred3))

[[91  2]
 [ 3 52]]


# RandomSearchCV LogisticRegression

In [48]:
from sklearn.model_selection import RandomizedSearchCV
reg1=RandomizedSearchCV(LogisticRegression(),{'C':[10,50,100]},cv=5,return_train_score='False',n_iter=3)
reg1.fit(x,y)

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=LogisticRegression(C=1.0, class_weight=None,
                                                dual=False, fit_intercept=True,
                                                intercept_scaling=1,
                                                l1_ratio=None, max_iter=100,
                                                multi_class='auto', n_jobs=None,
                                                penalty='l2', random_state=None,
                                                solver='lbfgs', tol=0.0001,
                                                verbose=0, warm_start=False),
                   iid='deprecated', n_iter=3, n_jobs=None,
                   param_distributions={'C': [10, 50, 100]},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score='False', scoring=None, verbose=0)

In [49]:
df=pd.DataFrame(reg1.cv_results_)
df

mean_fit_time  std_fit_time  ...  mean_train_score  std_train_score
0       0.047494      0.008283  ...          0.949916         0.008698
1       0.046611      0.007026  ...          0.951673         0.009301
2       0.050095      0.002182  ...          0.948157         0.005287

[3 rows x 21 columns]

In [50]:
df[['params','mean_test_score']]

params  mean_test_score
0   {'C': 10}         0.934964
1   {'C': 50}         0.936733
2  {'C': 100}         0.940289

In [51]:
reg2=LogisticRegression(C=1.0, class_weight=None,
                                                dual=False, fit_intercept=True,
                                                intercept_scaling=1,
                                                l1_ratio=None, max_iter=100,
                                                multi_class='auto', n_jobs=None,
                                                penalty='l2', random_state=None,
                                                solver='lbfgs', tol=0.0001,
                                                verbose=0, warm_start=False)
reg2.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [52]:
y_pred4=reg2.predict(x_test)

In [53]:
reg2.score(x_test,y_test)

0.9459459459459459

In [54]:
print(classification_report(y_test,y_pred4))

              precision    recall  f1-score   support

           0       0.98      0.94      0.96        93
           1       0.90      0.96      0.93        55

    accuracy                           0.95       148
   macro avg       0.94      0.95      0.94       148
weighted avg       0.95      0.95      0.95       148



In [55]:
print(confusion_matrix(y_test,y_pred4))

[[87  6]
 [ 2 53]]


# Bayesian Optimization

In [56]:
!pip install git+https://github.com/hyperopt/hyperopt-sklearn.git

  Cloning https://github.com/hyperopt/hyperopt-sklearn.git to /tmp/pip-req-build-qeed3mcg
  Running command git clone -q https://github.com/hyperopt/hyperopt-sklearn.git /tmp/pip-req-build-qeed3mcg
  Created wheel for hpsklearn: filename=hpsklearn-0.0.3-cp37-none-any.whl size=27011 sha256=6e91392b8dea4193788e989d4f33f52a688a9311362688d39acec07df3780973
  Stored in directory: /tmp/pip-ephem-wheel-cache-wkadhbm3/wheels/28/93/20/67dca95c2aaa13466b4900ba79a7bab66022e50ce44f8a438d
Successfully built hpsklearn


In [57]:
pip install hpsklearn

In [58]:
X_train,X_test,Y_train,Y_test=train_test_split(df_clean.drop(['encode_diag'],axis='columns') ,df_clean['encode_diag'],test_size=0.27,random_state=0)

In [59]:
from hpsklearn import HyperoptEstimator,any_classifier,any_preprocessing
from hyperopt import tpe
hpts=HyperoptEstimator(classifier=any_classifier('clf'),preprocessing=any_preprocessing('pre'),algo=tpe.suggest,max_evals=10)

WARN: OMP_NUM_THREADS=None =>
... If you are using openblas if you are using openblas set OMP_NUM_THREADS=1 or risk subprocess calls hanging indefinitely


In [60]:
hpts.fit(X_train,Y_train)

[19:43:39] WARNING: ../src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
100%|██████████| 1/1 [00:00<00:00, 10.58it/s, best loss: 0.0]
[19:43:42] WARNING: ../src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
100%|██████████| 1/1 [00:00<00:00,  4.01it/s, best loss: 0.0]


In [61]:
hpts.best_model()

{'ex_preprocs': (),
 'learner': GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                            learning_rate=0.014821098656603159, loss='deviance',
                            max_depth=None, max_features=0.2653585439759224,
                            max_leaf_nodes=None, min_impurity_decrease=0.0,
                            min_impurity_split=None, min_samples_leaf=27,
                            min_samples_split=2, min_weight_fraction_leaf=0.0,
                            n_estimators=156, n_iter_no_change=None,
                            presort='deprecated', random_state=4,
                            subsample=0.5524065399666254, tol=0.0001,
                            validation_fraction=0.1, verbose=0,
                            warm_start=False),
 'preprocs': (StandardScaler(copy=True, with_mean=False, with_std=False),)}

In [62]:
from sklearn.ensemble import GradientBoostingClassifier
gbc=GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                            learning_rate=0.014642752253745811, loss='deviance',
                            max_depth=None, max_features='sqrt',
                            max_leaf_nodes=None, min_impurity_decrease=0.0,
                            min_impurity_split=None, min_samples_leaf=1,
                            min_samples_split=2, min_weight_fraction_leaf=0.0,
                            n_estimators=102, n_iter_no_change=None,
                            presort='deprecated', random_state=3,
                            subsample=0.6217813737448401, tol=0.0001,
                            validation_fraction=0.1, verbose=0,
                            warm_start=False)
gbc.fit(X_train,Y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.014642752253745811, loss='deviance',
                           max_depth=None, max_features='sqrt',
                           max_leaf_nodes=None, min_impurity_decrease=0.0,
                           min_impurity_split=None, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=102, n_iter_no_change=None,
                           presort='deprecated', random_state=3,
                           subsample=0.6217813737448401, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [63]:
y_pred6=gbc.predict(X_test)

In [64]:
gbc.score(X_test,Y_test)

1.0

In [65]:
print(classification_report(Y_test,y_pred6))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        99
           1       1.00      1.00      1.00        55

    accuracy                           1.00       154
   macro avg       1.00      1.00      1.00       154
weighted avg       1.00      1.00      1.00       154



In [66]:
print(confusion_matrix(Y_test,y_pred6))

[[99  0]
 [ 0 55]]


# TPOT

In [67]:
!pip install tpot

In [68]:
from tpot import TPOTClassifier

In [69]:
model=TPOTClassifier(generations=5,population_size=50,cv=5,verbosity=2,random_state=0,scoring='accuracy')
model.fit(x,y)


Generation 1 - Current best internal CV score: 0.9683900015525537

Generation 2 - Current best internal CV score: 0.9754075454122031

Generation 3 - Current best internal CV score: 0.9754075454122031

Generation 4 - Current best internal CV score: 0.9771619313771154

Generation 5 - Current best internal CV score: 0.9771774569166279

Best pipeline: MLPClassifier(OneHotEncoder(RobustScaler(XGBClassifier(input_matrix, learning_rate=0.01, max_depth=2, min_child_weight=17, n_estimators=100, n_jobs=1, subsample=0.9000000000000001, verbosity=0)), minimum_fraction=0.1, sparse=False, threshold=10), alpha=0.0001, learning_rate_init=0.001)


TPOTClassifier(config_dict=None, crossover_rate=0.1, cv=5,
               disable_update_check=False, early_stop=None, generations=5,
               log_file=None, max_eval_time_mins=5, max_time_mins=None,
               memory=None, mutation_rate=0.9, n_jobs=1, offspring_size=None,
               periodic_checkpoint_folder=None, population_size=50,
               random_state=0, scoring='accuracy', subsample=1.0, template=None,
               use_dask=False, verbosity=2, warm_start=False)

In [70]:
model.score(x_test,y_test)

1.0

In [71]:
pip install xgboost

In [81]:
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import OneHotEncoder, RobustScaler
from xgboost import XGBClassifier
knn= MLPClassifier(OneHotEncoder(RobustScaler(XGBClassifier( learning_rate=0.01, max_depth=2, min_child_weight=17, n_estimators=100, n_jobs=1, subsample=0.9000000000000001, verbosity=0)), sparse=False), alpha=0.0001, learning_rate_init=0.001)

In [82]:
knn.fit(x_train,y_train)

TypeError: ignored

In [ ]:
y_pred5=knn.predict(x_test)  

In [ ]:
knn.score(x_test,y_test)

In [ ]:
print(classification_report(y_test,y_pred5))

In [ ]:
print(confusion_matrix(y_test,y_pred5))