# Importing Libraries

In [48]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Importing Dataset

In [87]:
df=pd.read_csv('/content/drive/MyDrive/ML Tasks/ADG-ML/data.csv')

In [50]:
df.head(5)

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [51]:
df.tail(5)

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
564  926424         M  ...                  0.07115          NaN
565  926682         M  ...                  0.06637          NaN
566  926954         M  ...                  0.07820          NaN
567  927241         M  ...                  0.12400          NaN
568   92751         B  ...                  0.07039          NaN

[5 rows x 33 columns]

In [88]:
#copying the datset values into another variable
df1=df.copy()
df1.head(5)

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [89]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Encoding the data

In [90]:
from sklearn.preprocessing import LabelEncoder
encode=LabelEncoder()
df1['encode_diag']=encode.fit_transform(df['diagnosis'])
df1['diagnosis']=df1['encode_diag']
df1.head(5)

id  diagnosis  ...  Unnamed: 32  encode_diag
0    842302          1  ...          NaN            1
1    842517          1  ...          NaN            1
2  84300903          1  ...          NaN            1
3  84348301          1  ...          NaN            1
4  84358402          1  ...          NaN            1

[5 rows x 34 columns]

# Getting the useful data

In [56]:
df_clean=df1.drop(['id','Unnamed: 32'],axis='columns')
df_clean.head(5)

diagnosis  radius_mean  ...  fractal_dimension_worst  encode_diag
0          1        17.99  ...                  0.11890            1
1          1        20.57  ...                  0.08902            1
2          1        19.69  ...                  0.08758            1
3          1        11.42  ...                  0.17300            1
4          1        20.29  ...                  0.07678            1

[5 rows x 32 columns]

# Splitting the dependent and independent variables

In [57]:
x=df_clean.iloc[:,1:-1]
x.head(5)

radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [58]:
y=df_clean.iloc[:,31]
y.head(5)

0    1
1    1
2    1
3    1
4    1
Name: encode_diag, dtype: int64

# Splitting into training and test dataset

In [59]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [60]:
x_train.count()

radius_mean                398
texture_mean               398
perimeter_mean             398
area_mean                  398
smoothness_mean            398
compactness_mean           398
concavity_mean             398
concave points_mean        398
symmetry_mean              398
fractal_dimension_mean     398
radius_se                  398
texture_se                 398
perimeter_se               398
area_se                    398
smoothness_se              398
compactness_se             398
concavity_se               398
concave points_se          398
symmetry_se                398
fractal_dimension_se       398
radius_worst               398
texture_worst              398
perimeter_worst            398
area_worst                 398
smoothness_worst           398
compactness_worst          398
concavity_worst            398
concave points_worst       398
symmetry_worst             398
fractal_dimension_worst    398
dtype: int64

In [61]:
y_train.count()

398

# Training the RandomForest onto to the dataset

In [62]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(random_state=0)
classifier.fit(x_train,y_train)
classifier.score(x_test,y_test)

0.9590643274853801

In [63]:
y_pred=classifier.predict(x_test)

In [64]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      0.96      0.97       108
           1       0.94      0.95      0.94        63

    accuracy                           0.96       171
   macro avg       0.95      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171



In [65]:
print(confusion_matrix(y_test,y_pred))

[[104   4]
 [  3  60]]


# Training Logistic regression onto the dataset

In [66]:
from sklearn.linear_model import LogisticRegression
regressor=LogisticRegression(random_state=0,max_iter=171)
regressor.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=171,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [67]:
y_pred=regressor.predict(x_test)

In [68]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.95      0.97       108
           1       0.93      0.98      0.95        63

    accuracy                           0.96       171
   macro avg       0.96      0.97      0.96       171
weighted avg       0.97      0.96      0.97       171



In [69]:
print(confusion_matrix(y_test,y_pred))

[[103   5]
 [  1  62]]


In [70]:
regressor.score(x_test,y_test)

0.9649122807017544

# GridSearchCV RandomForestClassifier

In [71]:
from sklearn.model_selection import GridSearchCV
clf=GridSearchCV(RandomForestClassifier(),{'n_estimators':[1,5,10]},cv=5,return_train_score='False')
clf.fit(x,y)

GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False,
                                              rando

In [72]:
df=pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  ...  mean_train_score  std_train_score
0       0.007607      0.005010  ...          0.966169         0.006891
1       0.011352      0.000205  ...          0.991215         0.003671
2       0.022022      0.001660  ...          0.997364         0.001645

[3 rows x 21 columns]

In [73]:
df[['params','mean_test_score']]

params  mean_test_score
0   {'n_estimators': 1}         0.915696
1   {'n_estimators': 5}         0.952601
2  {'n_estimators': 10}         0.952585

In [96]:
#training again to confirm values
classifier1=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False)
classifier1.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [100]:
y_pred1=classifier1.predict(x_test)

In [103]:
classifier1.score(x_test,y_test)

0.9649122807017544

In [102]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.98      0.96      0.97       108
           1       0.94      0.97      0.95        63

    accuracy                           0.96       171
   macro avg       0.96      0.97      0.96       171
weighted avg       0.97      0.96      0.97       171



In [114]:
print(confusion_matrix(y_test,y_pred1))

[[104   4]
 [  2  61]]


# GridSearchCV LogisticRegression

In [74]:
from sklearn.model_selection import GridSearchCV
reg=GridSearchCV(LogisticRegression(),{'C':[1,5,10]},cv=5,return_train_score='False')
reg.fit(x,y)

GridSearchCV(cv=5, error_score=nan,
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='deprecated', n_jobs=None, param_grid={'C': [1, 5, 10]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score='False',
             scoring=None, verbose=0)

In [75]:
df=pd.DataFrame(reg.cv_results_)
df

mean_fit_time  std_fit_time  ...  mean_train_score  std_train_score
0       0.056357      0.016297  ...          0.952989         0.008167
1       0.045079      0.009730  ...          0.949035         0.004875
2       0.040948      0.001642  ...          0.949916         0.008698

[3 rows x 21 columns]

In [76]:
df[['params','mean_test_score']]

params  mean_test_score
0   {'C': 1}         0.947291
1   {'C': 5}         0.938534
2  {'C': 10}         0.934964

In [110]:
reg1=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False)
reg1.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [111]:
y_pred2=reg1.predict(x_test)

In [112]:
reg1.score(x_test,y_test)

0.9590643274853801

In [113]:
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.98      0.95      0.97       108
           1       0.92      0.97      0.95        63

    accuracy                           0.96       171
   macro avg       0.95      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171



In [115]:
print(confusion_matrix(y_test,y_pred2))

[[103   5]
 [  2  61]]


# RandomSearchCV RandomForestclassifier

In [77]:
from sklearn.model_selection import RandomizedSearchCV
clf1=RandomizedSearchCV(RandomForestClassifier(),{'n_estimators':[10,50,100]},cv=5,return_train_score='False',n_iter=3)
clf1.fit(x,y)

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
               

In [78]:
df=pd.DataFrame(clf1.cv_results_)
df

mean_fit_time  std_fit_time  ...  mean_train_score  std_train_score
0       0.023438      0.002899  ...          0.994728          0.00357
1       0.104717      0.004849  ...          1.000000          0.00000
2       0.202290      0.007796  ...          1.000000          0.00000

[3 rows x 21 columns]

In [79]:
df[['params','mean_test_score']]

params  mean_test_score
0   {'n_estimators': 10}         0.949045
1   {'n_estimators': 50}         0.963096
2  {'n_estimators': 100}         0.957848

In [116]:
#training again to confirm values
classifier2=RandomForestClassifier(bootstrap=True,
                                                    ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
                                                    n_estimators=100,
                                                    n_jobs=None,
                                                    oob_score=False,
                                                    random_state=None,
                                                    verbose=0,
                                                    warm_start=False)
classifier2.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [117]:
y_pred3=classifier2.predict(x_test)

In [118]:
classifier2.score(x_test,y_test)

0.9649122807017544

In [119]:
print(classification_report(y_test,y_pred3))

              precision    recall  f1-score   support

           0       0.98      0.96      0.97       108
           1       0.94      0.97      0.95        63

    accuracy                           0.96       171
   macro avg       0.96      0.97      0.96       171
weighted avg       0.97      0.96      0.97       171



In [120]:
print(confusion_matrix(y_test,y_pred3))

[[104   4]
 [  2  61]]


# RandomSearchCV LogisticRegression

In [80]:
from sklearn.model_selection import RandomizedSearchCV
reg1=RandomizedSearchCV(LogisticRegression(),{'C':[10,50,100]},cv=5,return_train_score='False',n_iter=3)
reg1.fit(x,y)

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=LogisticRegression(C=1.0, class_weight=None,
                                                dual=False, fit_intercept=True,
                                                intercept_scaling=1,
                                                l1_ratio=None, max_iter=100,
                                                multi_class='auto', n_jobs=None,
                                                penalty='l2', random_state=None,
                                                solver='lbfgs', tol=0.0001,
                                                verbose=0, warm_start=False),
                   iid='deprecated', n_iter=3, n_jobs=None,
                   param_distributions={'C': [10, 50, 100]},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score='False', scoring=None, verbose=0)

In [81]:
df=pd.DataFrame(reg1.cv_results_)
df

mean_fit_time  std_fit_time  ...  mean_train_score  std_train_score
0       0.040380      0.003142  ...          0.949916         0.008698
1       0.046171      0.007571  ...          0.954309         0.007768
2       0.042937      0.001125  ...          0.945520         0.008606

[3 rows x 21 columns]

In [82]:
df[['params','mean_test_score']]

params  mean_test_score
0   {'C': 10}         0.934964
1   {'C': 50}         0.942012
2  {'C': 100}         0.947306

In [121]:
reg2=LogisticRegression(C=1.0, class_weight=None,
                                                dual=False, fit_intercept=True,
                                                intercept_scaling=1,
                                                l1_ratio=None, max_iter=100,
                                                multi_class='auto', n_jobs=None,
                                                penalty='l2', random_state=None,
                                                solver='lbfgs', tol=0.0001,
                                                verbose=0, warm_start=False)
reg2.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [122]:
y_pred4=reg2.predict(x_test)

In [123]:
reg2.score(x_test,y_test)

0.9590643274853801

In [124]:
print(classification_report(y_test,y_pred4))

              precision    recall  f1-score   support

           0       0.98      0.95      0.97       108
           1       0.92      0.97      0.95        63

    accuracy                           0.96       171
   macro avg       0.95      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171



In [125]:
print(confusion_matrix(y_test,y_pred4))

[[103   5]
 [  2  61]]


# Bayesian Optimization

In [83]:
!pip install git+https://github.com/hyperopt/hyperopt-sklearn.git

  Cloning https://github.com/hyperopt/hyperopt-sklearn.git to /tmp/pip-req-build-wjz4ttsk
  Running command git clone -q https://github.com/hyperopt/hyperopt-sklearn.git /tmp/pip-req-build-wjz4ttsk
  Created wheel for hpsklearn: filename=hpsklearn-0.0.3-cp37-none-any.whl size=27011 sha256=3bfb4ee94f39bf5c3cbebf06c0280360822cf30781e9c2b4a880809140862948
  Stored in directory: /tmp/pip-ephem-wheel-cache-i3rrq5pp/wheels/28/93/20/67dca95c2aaa13466b4900ba79a7bab66022e50ce44f8a438d
Successfully built hpsklearn


In [84]:
pip install hpsklearn

In [91]:
X_train,X_test,Y_train,Y_test=train_test_split(df_clean.drop(['encode_diag'],axis='columns') ,df_clean['encode_diag'],test_size=0.3,random_state=0)

In [92]:
from hpsklearn import HyperoptEstimator,any_classifier,any_preprocessing
from hyperopt import tpe
hpts=HyperoptEstimator(classifier=any_classifier('clf'),preprocessing=any_preprocessing('pre'),algo=tpe.suggest,max_evals=10)

In [93]:
hpts.fit(X_train,Y_train)

100%|██████████| 1/1 [00:02<00:00,  2.55s/it, best loss: 0.0]


In [94]:
hpts.best_model()

{'ex_preprocs': (),
 'learner': GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                            learning_rate=0.014642752253745811, loss='deviance',
                            max_depth=None, max_features='sqrt',
                            max_leaf_nodes=None, min_impurity_decrease=0.0,
                            min_impurity_split=None, min_samples_leaf=1,
                            min_samples_split=2, min_weight_fraction_leaf=0.0,
                            n_estimators=102, n_iter_no_change=None,
                            presort='deprecated', random_state=3,
                            subsample=0.6217813737448401, tol=0.0001,
                            validation_fraction=0.1, verbose=0,
                            warm_start=False),
 'preprocs': (Normalizer(copy=True, norm='l1'),)}

In [148]:
from sklearn.ensemble import GradientBoostingClassifier
gbc=GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                            learning_rate=0.014642752253745811, loss='deviance',
                            max_depth=None, max_features='sqrt',
                            max_leaf_nodes=None, min_impurity_decrease=0.0,
                            min_impurity_split=None, min_samples_leaf=1,
                            min_samples_split=2, min_weight_fraction_leaf=0.0,
                            n_estimators=102, n_iter_no_change=None,
                            presort='deprecated', random_state=3,
                            subsample=0.6217813737448401, tol=0.0001,
                            validation_fraction=0.1, verbose=0,
                            warm_start=False)
gbc.fit(x_train,y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.014642752253745811, loss='deviance',
                           max_depth=None, max_features='sqrt',
                           max_leaf_nodes=None, min_impurity_decrease=0.0,
                           min_impurity_split=None, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=102, n_iter_no_change=None,
                           presort='deprecated', random_state=3,
                           subsample=0.6217813737448401, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [151]:
y_pred6=knn.predict(x_test)

In [150]:
knn.score(x_test,y_test)

0.935672514619883

In [152]:
print(classification_report(y_test,y_pred6))

              precision    recall  f1-score   support

           0       0.92      0.98      0.95       108
           1       0.96      0.86      0.91        63

    accuracy                           0.94       171
   macro avg       0.94      0.92      0.93       171
weighted avg       0.94      0.94      0.93       171



In [153]:
print(confusion_matrix(y_test,y_pred6))

[[106   2]
 [  9  54]]


# TPOT

In [126]:
!pip install tpot

In [127]:
from tpot import TPOTClassifier

In [128]:
model=TPOTClassifier(generations=5,population_size=50,cv=5,verbosity=2,random_state=0,scoring='accuracy')
model.fit(x,y)


Generation 1 - Current best internal CV score: 0.9683900015525537

Generation 2 - Current best internal CV score: 0.9754075454122031

Generation 3 - Current best internal CV score: 0.9754075454122031

Generation 4 - Current best internal CV score: 0.9754075454122031

Generation 5 - Current best internal CV score: 0.9771774569166277

Best pipeline: MLPClassifier(KNeighborsClassifier(RobustScaler(RobustScaler(input_matrix)), n_neighbors=48, p=2, weights=uniform), alpha=0.0001, learning_rate_init=0.001)


TPOTClassifier(config_dict=None, crossover_rate=0.1, cv=5,
               disable_update_check=False, early_stop=None, generations=5,
               log_file=None, max_eval_time_mins=5, max_time_mins=None,
               memory=None, mutation_rate=0.9, n_jobs=1, offspring_size=None,
               periodic_checkpoint_folder=None, population_size=50,
               random_state=0, scoring='accuracy', subsample=1.0, template=None,
               use_dask=False, verbosity=2, warm_start=False)

In [129]:
model.score(x_test,y_test)

1.0

In [141]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import RobustScaler
knn=KNeighborsClassifier( n_neighbors=48, p=2,weights='uniform')

In [142]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=48, p=2,
                     weights='uniform')

In [143]:
y_pred5=knn.predict(x_test)

In [144]:
knn.score(x_test,y_test)

0.935672514619883

In [145]:
print(classification_report(y_test,y_pred5))

              precision    recall  f1-score   support

           0       0.92      0.98      0.95       108
           1       0.96      0.86      0.91        63

    accuracy                           0.94       171
   macro avg       0.94      0.92      0.93       171
weighted avg       0.94      0.94      0.93       171



In [146]:
print(confusion_matrix(y_test,y_pred5))

[[106   2]
 [  9  54]]
